<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\ArticlesController as SimpleArticleController;
use App\Http\Requests\ArticleRequest;
use App\Models\Article;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Session;
use Illuminate\View\View;

/**
 * Контроллер для работы со статьями в админке
 *
 * Class ArticlesController
 * @package App\Http\Controllers\Admin
 */
class ArticlesController extends SimpleArticleController
{
    /**
     * Опубликованные статьи
     *
     * @return View
     */
    public function published() : View
    {
        $articles = Article::published()->with('user')->orderByDesc('created_at')->get();
        $title = __('knowledgebase.published_articles');

        return view('admin.articles.index', compact('articles', 'title'));
    }

    /**
     * Отклонённые или удалённые статьи
     *
     * @return View
     */
    public function rejectedAndDeleted() : View
    {
        $articles = Article::rejectedAndDeleted()->with('user')->orderByDesc('created_at')->get();
        $title = __('knowledgebase.rejected_deleted_articles');

        return view('admin.articles.index', compact('articles', 'title'));
    }

    /**
     * Непроверенные статьи
     *
     * @return View
     */
    public function unchecked() : View
    {

        $articles = Article::unchecked()->with('user')->orderByDesc('created_at')->get();
        $title = __('knowledgebase.unchecked_articles');


        return view('admin.articles.index', compact('articles', 'title'));
    }

    /**
     * Верификация статьи
     *
     * @param Article $article
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function verify(Article $article, Request $request)
    {
        try {
            $article->checked_by_admin = true;
            $article->published = $request->has('publicate');

            if ($request->has('publicate')) {
                $article->restore();
            }

            if (!$article->save()) {
                Session::flash('error', __('knowledgebase.errors.is_not_publicated'));

                Log::error("Не удалось провести действие над статьёй", ['article' => $article->toJson()]);
            }
        } catch (\Exception $e) {
            Session::flash('error', __('knowledgebase.errors.is_not_publicated'));

            Log::error("Не удалось провести действие над статьёй", [
                'message' => $e->getMessage(),
                'code'    => $e->getCode(),
                'trace'   => $e->getTrace()
            ]);
        } finally {
            return redirect()->back();
        }
    }

    public function show(Article $article, $fromAdmin = true)
    {
        return parent::show($article, $fromAdmin);
    }

    public function edit(Article $article)
    {
        return parent::edit($article); // TODO: Change the autogenerated stub
    }

    public function destroy(Article $article, $redirectBack = true)
    {
        return parent::destroy($article, true);
    }
}
